version: "1"
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    restart: always
    ports:
      - "127.0.0.1:2181:2181"

  kafka:
    depends_on:
      - zookeeper
    image: wurstmeister/kafka:2.13-2.8.1
    restart: always
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_CREATE_TOPICS=sas:1:1
    ports:
      - "127.0.0.1:9092:9092"

  gateway-service:
    build: ./gateway
    image: martel42/gateway-service:v1.0
    container_name: gateway-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    depends_on:
      - kafka

  auth-service:
    build: ./auth
    image: martel42/auth-service:v1.0
    container_name: auth-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8079:8079"
    depends_on:
      - gateway-service
  stats-service:
    build: ./stats
    image: martel42/stats-service
    container_name: stats-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8081"
    depends_on:
      - gateway-service

  user-service:
    build: ./user
    image: martel42/user-service:v1.0
    container_name: user-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8082:8082"
    depends_on:
      - gateway-service

  blog-service:
    build: ./blog
    image: martel42/blog-service
    container_name: blog-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8083:8083"
    depends_on:
      - gateway-service
  post-service:
    build: ./post
    image: martel42/post-service:v1.0
    container_name: post-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8084:8084"
    depends_on:
      - blog-service

  subs-service:
    build: ./subs
    image: martel42/subs-service
    container_name: subs-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8085:8085"
    depends_on:
      - user-service

