version: "1"
services:
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    restart: always
    ports:
      - "127.0.0.1:2181:2181"

  kafka:
    depends_on:
      - zookeeper
    image: wurstmeister/kafka:2.13-2.8.1
    restart: always
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_HOST_NAME=localhost
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_CREATE_TOPICS=sas:1:1
    ports:
      - "127.0.0.1:9092:9092"

  gateway-service:
    build: ./gateway
    image: martel42/gateway-service:v1.0
    container_name: gateway-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    depends_on:
      - kafka

  stats-service:
    build: ./stats
    image: martel42/stats-service
    container_name: stats-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8081:8081"
    depends_on:
      - gateway-service

